import { Asset } from './asset';

export let ASSETS: Asset[] = [
    {
        "id": 1,
        "path": "../assets/images/a45-amg.jpg",
        "width": 1024,
        "height": 682
    }, {
        "id": 2,
        "path": "../assets/images/c120.jpg",
        "width": 1230,
        "height": 582
    }, {
        "id": 3,
        "path": "../assets/images/c232.jpg",
        "width": 800,
        "height": 530
    }, {
        "id": 4,
        "path": "../assets/images/daimler_1886.jpg",
        "width": 800,
        "height": 530
    }, {
        "id": 5,
        "path": "../assets/images/daimler_cla_mercedes.jpg",
        "width": 568,
        "height": 237
    }, {
        "id": 6,
        "path": "../assets/images/daimler_star.jpg",
        "width": 450,
        "height": 300
    }, {
        "id": 7,
        "path": "../assets/images/F-015-Luxury.jpg",
        "width": 1180,
        "height": 559
    }, {
        "id": 8,
        "path": "../assets/images/mercedes-amg-gt-5.jpg",
        "width": 900,
        "height": 600
    }, {
        "id": 9,
        "path": "../assets/images/Mercedes-Benz_GLK-Klasse.jpg",
        "width": 799,
        "height": 532
    }, {
        "id": 10,
        "path": "../assets/images/mercedes-benz-a-class-w176.jpg",
        "width": 814,
        "height": 383
    }, {
        "id": 11,
        "path": "../assets/images/mercedes-benz-cla-class-117.jpg",
        "width": 740,
        "height": 295
    }, {
        "id": 12,
        "path": "../assets/images/mercedes-benz-sf1.jpg",
        "width": 620,
        "height": 361
    }, {
        "id": 13,
        "path": "../assets/images/mercedes-cls.jpg",
        "width": 610,
        "height": 343
    }, {
        "id": 14,
        "path": "../assets/images/slk-200.jpg",
        "width": 630,
        "height": 420
    }, {
        "id": 15,
        "path": "../assets/images/van.jpg",
        "width": 960,
        "height": 298
    }, {
        "id": 16,
        "path": "../assets/images/w180.jpg",
        "width": 1000,
        "height": 563
    }, {
        "id": 17,
        "path": "../assets/images/z100.jpg",
        "width": 510,
        "height": 335
    }
];
